language: node_js
node_js:
- node
cache: npm
stages:
- name: version
  if: "(type = pull_request AND branch = master) OR (branch = master)"
- name: install
  if: "(type = pull_request) or branch = master"
- name: coverage
  if: "(type = pull_request)"
- name: send-coverage
  if: branch = master
- name: deploy-npm
  if: "(branch = master) AND (type = push)"
jobs:
  include:
  - stage: version
    before_script:
    - chmod +x .travis/validate-version.js
    script:
    - node .travis/validate-version.js
  - stage: install
    script: yarn install
  - stage: coverage
    script:
    - yarn install-test-client
    - yarn test:cypress:install
    - yarn test:update-test-client
    - yarn test:coverage
  - stage: send-coverage
    script:
    - yarn install-test-client
    - yarn test:cypress:install
    - yarn test:update-test-client
    - yarn test:coverage
    - yarn send-coverage
  - stage: deploy-npm
    script:
    - yarn install
    deploy:
      provider: npm
      email: "$ENV_EMAIL"
      api_key:
        secure: s423eOFEtf/tufhWga5Eb2Vr5Jx/VJawP0rhASp2cTpFESRrTN8NqGlvCw9JwcrjWr/bI/rGrTBwNdQl0W0bM/qAFW4s5jZ2VPT6iBkQVzY4vUZHd2ebSeJCnNoleBwMKvDb1jvBEFeOcnX8dsH/9yb7aq+yNk1HHGHiZyyCHCrk8QwXH7gisB6DECQx0dv464F0SnDMHRWP+UtRajOTR71UJ5N3nO62Y8E2BSEMaf/Crj9AYchLTAYZpVGaJe5BNx6cUolbPa1RpvS4WLDuB6XrcOxtBysv9zPP2PeOPTlbbBwNjnTJsZ9Kb6Zh8AD2u+Qg7jxUF8IatPDKDah/PsNjZchEmAn7+4k3mxtC187qBMOidtIqpeJBB63os6TtXKAUC25K0gESfNxzhvjZub6rhHcAXcpvZToL7orFspVegb9V/JSYhl1XcpC/NJPtaHLogqRbb+LGskQoS7Q4IyOlTzgPaUSwu3unle8T6EHLPWSze5dP2nBXuw7k83HidXrWEGuz4QZadmuATfoBqLManuZywhejePChNX2AXHto6K+5SRaYB1KO+gEZKxNLyKOzs2LDWW1Sp00efS2wkkfQS4z1iiqUH/TfMjX1vKJl48aMAu6oKQRc0Nrpi60PdBF8WNtBOfQobK2T3XvGRs3NEutTZ1NfhlfnGhwyNCE=
      skip_cleanup: 'true'